# -*- coding: utf-8 -*-
"""Streamlit run app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-qdwNmwZ0TJ1klLHTXA_7E8oXcHSe06
"""

import os
import sys
import time
import subprocess
from google.colab import userdata

print("🚀 [1/5] Installing system dependencies & compiling pgvector extension...")
!apt-get update -qq > /dev/null
!apt-get install -y build-essential git postgresql-16 postgresql-server-dev-16 > /dev/null

!rm -rf /tmp/pgvector
!git clone https://github.com/pgvector/pgvector.git /tmp/pgvector > /dev/null 2>&1
!cd /tmp/pgvector && make > /dev/null 2>&1 && make install > /dev/null 2>&1

!wget -q -N https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb > /dev/null 2>&1

print("📦 [2/5] Installing Python packages...")
!{sys.executable} -m pip install --quiet --upgrade \
    streamlit \
    langchain-core \
    langchain-community \
    langchain-openai \
    langchain-text-splitters \
    pypdf \
    psycopg2-binary \
    pgvector

print("🐘 [3/5] Starting PostgreSQL service & resetting database...")
!service postgresql start > /dev/null
!sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'mysecretpassword';" > /dev/null
!sudo -u postgres psql -c "DROP DATABASE IF EXISTS vectordb;" > /dev/null
!sudo -u postgres psql -c "CREATE DATABASE vectordb;" > /dev/null
!sudo -u postgres psql -d vectordb -c "CREATE EXTENSION IF NOT EXISTS vector;" > /dev/null

print("📝 [4/5] Writing pure Streamlit app.py script...")
app_code = """import streamlit as st
import os
import tempfile
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import PGVector
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

st.set_page_config(page_title="Multi-Document Q&A", page_icon="📚", layout="wide")
st.title("📚 Multi-Document Q&A App")

if "OPENAI_API_KEY" not in os.environ or not os.environ["OPENAI_API_KEY"]:
    st.error("OpenAI API Key is missing. Please set OPENAI_API_KEY in Colab Secrets.")
    st.stop()

CONNECTION_STRING = "postgresql+psycopg2://postgres:mysecretpassword@localhost:5432/vectordb"

uploaded_files = st.file_uploader("Upload PDF documents", type="pdf", accept_multiple_files=True)

if uploaded_files:
    file_names = sorted([f.name for f in uploaded_files])

    # Check if active upload files changed
    if st.session_state.get("current_files") != file_names:
        st.session_state["current_files"] = file_names
        if "vectorstore" in st.session_state:
            del st.session_state["vectorstore"]

    if "vectorstore" not in st.session_state:
        with st.spinner(f"Processing {len(uploaded_files)} document(s) in FIFO order..."):
            try:
                all_documents = []
                for uploaded_file in uploaded_files:
                    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                        tmp_file.write(uploaded_file.getvalue())
                        tmp_path = tmp_file.name

                    loader = PyPDFLoader(tmp_path)
                    docs = loader.load()
                    all_documents.extend(docs)
                    os.remove(tmp_path)

                text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
                texts = text_splitter.split_documents(all_documents)

                embeddings = OpenAIEmbeddings()

                vectorstore = PGVector.from_documents(
                    documents=texts,
                    embedding=embeddings,
                    connection_string=CONNECTION_STRING,
                    collection_name="pdf_documents",
                    pre_delete_collection=True
                )

                st.session_state["vectorstore"] = vectorstore
                st.success(f"Indexed {len(uploaded_files)} document(s) into PostgreSQL vector database!")
            except Exception as e:
                st.error(f"Ingestion Error: {e}")
                st.stop()

st.divider()
question = st.text_input("Ask a question across all uploaded documents:")

if question:
    if "vectorstore" in st.session_state:
        with st.spinner("Searching vector database across all documents..."):
            try:
                retriever = st.session_state["vectorstore"].as_retriever(search_kwargs={"k": 5})

                def format_docs(docs):
                    return "\\n\\n".join(doc.page_content for doc in docs)

                prompt = ChatPromptTemplate.from_template(
                    "Answer the question based strictly on the provided context:\\n\\n"
                    "Context:\\n{context}\\n\\n"
                    "Question: {question}"
                )

                llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

                rag_chain = (
                    {"context": retriever | format_docs, "question": RunnablePassthrough()}
                    | prompt
                    | llm
                    | StrOutputParser()
                )

                response = rag_chain.invoke(question)
                st.markdown("### Answer:")
                st.write(response)
            except Exception as e:
                st.error(f"QA Error: {e}")
    else:
        st.warning("Please upload at least one PDF document first.")
"""

with open("app.py", "w") as f:
    f.write(app_code)

print("🌐 [5/5] Starting Streamlit server & Cloudflare Tunnel...")
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

!pkill -9 -f streamlit
!pkill -9 -f cloudflared

log_file = open("logs.txt", "w")
subprocess.Popen(
    [sys.executable, "-m", "streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "127.0.0.1"],
    stdout=log_file,
    stderr=subprocess.STDOUT
)

time.sleep(6)
log_file.close()

!cloudflared tunnel --url http://127.0.0.1:8501