# -*- coding: utf-8 -*-
"""Streamlit run app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-qdwNmwZ0TJ1klLHTXA_7E8oXcHSe06
"""

import os
import tempfile
import streamlit as st
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import PGVector
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

st.set_page_config(page_title="Multi-Document Q&A", page_icon="📚", layout="wide")
st.title("📚 Multi-Document Q&A App")

# Retrieve secrets/environment variables safely
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
CONNECTION_STRING = os.getenv(
    "DATABASE_URL",
    "postgresql+psycopg2://postgres:mysecretpassword@localhost:5432/vectordb"
)

if not OPENAI_API_KEY:
    st.error("OpenAI API Key is missing. Please set OPENAI_API_KEY in your deployment environment secrets.")
    st.stop()

uploaded_files = st.file_uploader("Upload PDF documents", type="pdf", accept_multiple_files=True)

if uploaded_files:
    file_names = sorted([f.name for f in uploaded_files])

    # Reset vectorstore if file selection changes
    if st.session_state.get("current_files") != file_names:
        st.session_state["current_files"] = file_names
        if "vectorstore" in st.session_state:
            del st.session_state["vectorstore"]

    if "vectorstore" not in st.session_state:
        with st.spinner(f"Processing {len(uploaded_files)} document(s) in FIFO order..."):
            try:
                all_documents = []
                for uploaded_file in uploaded_files:
                    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                        tmp_file.write(uploaded_file.getvalue())
                        tmp_path = tmp_file.name

                    loader = PyPDFLoader(tmp_path)
                    docs = loader.load()
                    all_documents.extend(docs)
                    os.remove(tmp_path)

                text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
                texts = text_splitter.split_documents(all_documents)

                embeddings = OpenAIEmbeddings()

                vectorstore = PGVector.from_documents(
                    documents=texts,
                    embedding=embeddings,
                    connection_string=CONNECTION_STRING,
                    collection_name="pdf_documents",
                    pre_delete_collection=True
                )

                st.session_state["vectorstore"] = vectorstore
                st.success(f"Indexed {len(uploaded_files)} document(s) into PostgreSQL vector database!")
            except Exception as e:
                st.error(f"Ingestion Error: {e}")
                st.stop()

st.divider()
question = st.text_input("Ask a question across all uploaded documents:")

if question:
    if "vectorstore" in st.session_state:
        with st.spinner("Searching vector database across all documents..."):
            try:
                retriever = st.session_state["vectorstore"].as_retriever(search_kwargs={"k": 5})

                def format_docs(docs):
                    return "\n\n".join(doc.page_content for doc in docs)

                prompt = ChatPromptTemplate.from_template(
                    "Answer the question based strictly on the provided context:\n\n"
                    "Context:\n{context}\n\n"
                    "Question: {question}"
                )

                llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

                rag_chain = (
                    {"context": retriever | format_docs, "question": RunnablePassthrough()}
                    | prompt
                    | llm
                    | StrOutputParser()
                )

                response = rag_chain.invoke(question)
                st.markdown("### Answer:")
                st.write(response)
            except Exception as e:
                st.error(f"QA Error: {e}")
    else:
        st.warning("Please upload at least one PDF document first.")